require_relative "./mlb_standings/version"
require_relative "./mlb_standings/league"
require_relative "./mlb_standings/division"
require_relative "./mlb_standings/team"
require_relative "./mlb_standings/cli"